services:
  api:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    volumes:
      - ./:/go/src/kotatuneko-rest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: postgres:16.3
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    healthcheck: # here
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${DB_USER}",
          "-h",
          "${DB_HOST}",
          "-d",
          "${DB_NAME}",
        ]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - "8081:8080"
volumes:
  db-store:
