services:
  api:
    build:
      context: .
      dockerfile: docker/develop/Dockerfile
    volumes:
      - ./:/go/src/kotatuneko-rest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - HOSTNAME=${HOSTNAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck: # here
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-h",
          "${HOSTNAME}",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}",
        ]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - "8081:8080"
volumes:
  db-store:
