basePath: /
host: localhost:8080
info:
  contact: {}
  description: こたつねこの REST API
  license:
    name: BSD-3-Clause license
    url: https://github.com/rayfiyo/kotatuneko-rest?tab=BSD-3-Clause-1-ov-file
  termsOfService: http://localhost:8080/
  title: Kotatuneko REST API
  version: "1.0"
paths:
  /:
    get:
      operationId: HelloWorldIndex
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Hello World !
      tags:
      - HelloWorld
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
